### ISSUE TITLE
README Functionality Section Issues

### ISSUE THREAD

**Issue by ijbd** [9505-PNNL/wmpy_power#1]
![image](https://github.com/user-attachments/assets/0c09aa61-9a47-4104-9fd5-20750cf19933)

#openjournals/joss-reviews#7225

**Comment by ijbd** [comment]
On first read, the penstock flexibility, $f_p$, doesn't appear to be used, and an undefined subscript $f_f$ is used instead. 

![image](https://github.com/user-attachments/assets/dece6045-134b-454b-8439-e5390cd38bb7)

**Comment by ijbd** [comment]
Similar issues on Equations 7 through 11 (although I don't see Equation 9).

![image](https://github.com/user-attachments/assets/ee105ca9-334e-455d-82c3-164ea8d50e33)

**Comment by thurber** [comment]
Thanks for the feedback! @danbroman can you review and update the equations as needed?

**Comment by danbroman** [comment]
@ijbd thanks for the review. i believe i addressed the errors you found - the Qmax formula was incomplete, and f_m should have been f_p. please let me know if you see any other issues
